name: Auto Versioning Test Suite

on: push

jobs:
  test_case_1:
    name: initial version tag is created if no tags exist
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove all tags
        run: |
          # Delete all local tags
          git fetch --tags
          git tag -l | xargs git tag -d
          # Fetch the list of remote tags and then push a command to delete each of them on the remote repository
          git push origin $(git ls-remote --tags origin | awk '{print ":" $2}')

      - name: Increment Version
        id: increment_version
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if new tag is '0.0.1'
        run: |
          ACTION_OUTPUT=${{ steps.increment_version.outputs.build-version }}
          test ${ACTION_OUTPUT} = '0.0.1'
          git fetch --tags
          test $(git tag --points-at HEAD) = '0.0.1'


  test_case_2:
    name: build version is incremented if a tag was found
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test_case_1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove all tags
        run: |
          # Delete all local tags
          git fetch --tags
          git tag -l | xargs git tag -d
          # Fetch the list of remote tags and then push a command to delete each of them on the remote repository
          git push origin $(git ls-remote --tags origin | awk '{print ":" $2}')

      - name: Push test tag '1.3.139'
        run: |
          git tag '1.3.139'
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Increment Version
        id: increment_version
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if new tag is '1.3.140'
        run: |
          ACTION_OUTPUT=${{ steps.increment_version.outputs.build-version }}
          test ${ACTION_OUTPUT} = '1.3.140'
          git fetch --tags
          test $(git tag --points-at HEAD) = '1.3.140'
