name: Auto Versioning Test Suite

on:
  push:
    paths:
      - 'action.yml'

jobs:
  test_case_1:
    name: Test action on a fresh repo with no existing tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and remove all tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove all tags
        run: git tag | xargs git tag -d

      - name: Increment Version
        id: increment_version
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all tags again
        run: git fetch --tags

      - name: Check if new tag is '1'
        run: test ${NEW_VERSION} = '1'
        env:
          NEW_VERSION: ${{ steps.increment_version.outputs.build_version }}

  test_case_2:
    name: Test action on a repo with an initial tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set tag to '5'
        run: git tag '5'

      - name: Increment Version
        id: increment_version
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all tags again
        run: git fetch --tags

      - name: Check if new tag is '6'
        run: test ${NEW_VERSION} = '6'
        env:
          NEW_VERSION: ${{ steps.increment_version.outputs.build_version }}